# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alberto Guadalupe Rivas Pérez
title: Estudiante
email: alberto.rivp@gmail.com
website: albertorivp.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  AlbertoRivp
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Alberto and I'm barely a student, I know a little bit of everything and nothing at all!
  


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/albertorivp.github.io
        # link_text: Project Website
        additional_links:
#          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          lorem15
        description: | # this will include new lines to allow paragraphs
          This is a placeholder, will be removed later!

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2021 - Today
        sub_title: BSc Computer Science
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        quote: >
          I don't know what to tell you, but this will mean something in the future!
        description: | # this will include new lines to allow paragraphs
           I'm trying my best to not perish while I'm here.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I'm here to exist.

      Also, look at this image.

      ![Trees](/images/cool_background.jpg "Hallstatt, Austria (By Sheng L at unsplash)")
    additional_links:
      title: Hallstatt, Austria (By Sheng L at unsplash)  
      icon: fab fa-unsplash
      url: unsplash.com/photos/yDEdUjYhR-4

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
